### ISSUE TITLE
Incorrect plug-in name listed in Readme instructions and no GraphQL example

### ISSUE THREAD

**Issue by jdebettencourt** [ftavares/gatsby-source-openweathermap#1]
The instructions from the Readme.md for this plug-in have you trying to install a non-existent plug-in

Both the yarn command and the plug-in module command reference the mis-named: 
gatsby-source-openweatherapi

If instead you use as the plug-in name the name of this repository:
gatsby-source-openweathermap

Everything seems to work (after getting a key) and working out a GraphQL query to include like:

{
  openWeather {
    cod
    cnt
    city {
      id
      population
    }
    list {
      dt
      dt_txt
      weather {
        id
        main
      }
      main {
        temp
        temp_min
        temp_max
        pressure
        sea_level
        grnd_level
        humidity
        temp_kf
      }
      rain {
        _3h
      }
    }
  }
}

Haven't submitted an issue before, so I hope this will be useful.

**Comment by ftavares** [comment]
Hi @jdebettencourt ,

Thank you for reporting this.

This issues is fix and published now.

Thank you.
@ftavares

**Comment by jdebettencourt** [comment]
Thank you for the quick response and fix.
